using SkimSkript.LexicalAnalysis.Helpers;
using SkimSkript.TokenManagement;

namespace SkimSkript.LexicalAnalysis
{
    /// <summary>Coordinates lexeme scanning and evaluation to produce tokens.
    /// Populates a <see cref="TokenManagement.TokenContainer"/> using input lines.</summary>
    public class Lexer
    {
        private Scanner _scanner;
        private Evaluator _evaluator;

        /// <summary>Structure containing the tokens generated by using the lexeme data.</summary>
        public TokenContainer TokenContainer => _evaluator.TokenContainer;

        /// <summary>Constructor that performs lexical analysis using lines of code in the source language.</summary>
        /// <param name="linesArray">Lines of code in the source language.</param>
        public Lexer(string[] linesArray)
        {
            _scanner = new Scanner(linesArray);
            _evaluator = new Evaluator(_scanner.LexemeDataList);
        }
    }
}
